/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { DirectionalLight, HemisphereLight } from 'three'

export default function Spline({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/BVZyuOcOPcnAPAP1/scene.splinecode')
  return (
    <Canvas>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="Blob 2"
            geometry={nodes['Blob 2'].geometry}
            material={materials['Blob 2 Material']}
            position={[-24, 42, -2267.27]}
          />
          <mesh
            name="Blob 1"
            geometry={nodes['Blob 1'].geometry}
            material={materials['Blob 1 Material']}
            position={[-42, 18.84, -1068.52]}
          />
          <group name="Group" position={[0, 0, 75]} rotation={[-0.7, 0.7, 0.7]}>
            <mesh
              name="Banner"
              geometry={nodes.Banner.geometry}
              material={materials['Banner Material']}
              castShadow
              receiveShadow
              position={[39.75, 252.84, -65]}
            />
            <mesh
              name="Aavatar"
              geometry={nodes.Aavatar.geometry}
              material={materials['Aavatar Material']}
              castShadow
              receiveShadow
              position={[517, 274, -65]}
            />
            <mesh
              name="Feature 1"
              geometry={nodes['Feature 1'].geometry}
              material={materials['Feature 1 Material']}
              castShadow
              receiveShadow
              position={[-136.16, -11.19, -65]}
            />
            <mesh
              name="Feature 2"
              geometry={nodes['Feature 2'].geometry}
              material={materials['Feature 2 Material']}
              castShadow
              receiveShadow
              position={[210.98, -11.19, -65]}
            />
            <mesh
              name="Popular 1"
              geometry={nodes['Popular 1'].geometry}
              material={materials['Popular 1 Material']}
              castShadow
              receiveShadow
              position={[-136.07, -262.19, -65]}
            />
            <mesh
              name="Popular 2"
              geometry={nodes['Popular 2'].geometry}
              material={materials['Popular 2 Material']}
              castShadow
              receiveShadow
              position={[210.38, -262.19, -65]}
            />
            <mesh
              name="Member 4"
              geometry={nodes['Member 4'].geometry}
              material={materials['Member 4 Material']}
              castShadow
              receiveShadow
              position={[517.93, -154.06, -65]}
            />
            <mesh
              name="Member 3"
              geometry={nodes['Member 3'].geometry}
              material={materials['Member 3 Material']}
              castShadow
              receiveShadow
              position={[517.93, -85.63, -65]}
            />
            <mesh
              name="Member 2"
              geometry={nodes['Member 2'].geometry}
              material={materials['Member 2 Material']}
              castShadow
              receiveShadow
              position={[517.93, -17.41, -65]}
            />
            <mesh
              name="Member 1"
              geometry={nodes['Member 1'].geometry}
              material={materials['Member 1 Material']}
              castShadow
              receiveShadow
              position={[517.93, 51.81, -65]}
            />
            <mesh
              name="Background"
              geometry={nodes.Background.geometry}
              material={materials['Background Material']}
              receiveShadow
              position={[0, 0, -75]}
              scale={[1, 1, 2.51]}
            />
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.5}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-750}
            shadow-camera-right={750}
            shadow-camera-top={750}
            shadow-camera-bottom={-750}
            position={[202.36, 293.2, 1112.17]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </Canvas>
  )
}
